# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achive',
            fields=[
                ('aid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('pic', models.URLField(null=True)),
                ('pubdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('mid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('face', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='achive',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilibili.Owner'),
        ),
    ]
