# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilibili', '0002_auto_20170512_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
