# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liepin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cata',
            fields=[
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('python', models.BooleanField()),
                ('spider', models.BooleanField()),
                ('datemine', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='benefit',
            field=models.CharField(max_length=80),
        ),
    ]
