# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liepin', '0002_auto_20170506_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cata',
            name='datemine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cata',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cata',
            name='spider',
            field=models.BooleanField(default=False),
        ),
    ]
