# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liepin', '0004_auto_20170506_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cata',
            name='data',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cata',
            name='python',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cata',
            name='spider',
            field=models.NullBooleanField(default=False),
        ),
    ]
