# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liepin', '0005_auto_20170506_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='data',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='python',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='spider',
            field=models.NullBooleanField(default=False),
        ),
    ]
