# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('by', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
