# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('pid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=10)),
                ('requirement', models.TextField()),
                ('benefit', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
                ('labels', models.CharField(max_length=40)),
                ('catagory', models.CharField(max_length=10)),
                ('companylink', models.URLField(null=True)),
            ],
        ),
    ]
