# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=10)),
                ('requirement', models.TextField()),
                ('benefit', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=10)),
                ('labels', models.CharField(max_length=40)),
                ('catagory', models.CharField(max_length=10)),
            ],
        ),
    ]
