# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='catagory',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
