# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagou', '0001_initial'),
    ]

    operations = [

    ]
