# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagou', '0002_position_companylink'),
    ]

    operations = [
    ]
