# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('update_time', models.DateField()),
                ('vid', models.CharField(max_length=15)),
                ('img', models.URLField()),
                ('rank', models.IntegerField()),
                ('intro', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=15)),
            ],
        ),
    ]
