# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
