# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170418_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='label',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
