# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20170418_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='intro',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='series',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
