# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20170422_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='label',
            field=models.CharField(default='null', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='rank',
            field=models.IntegerField(default='100', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='series',
            field=models.CharField(default='null', max_length=64, null=True),
        ),
    ]
